/**
 * Created by martin on 21/07/2017.
 */

var shelters = [
    {
        title: 'Bethany House',
        location: {lat: 55.976019, lng: -3.176873},
        address: '12 Couper Street',
        phone: '0131 561 8911',
        email: 'info@bethanychristiantrust.com',
        wiki: 'https://en.wikipedia.org/wiki/Bethany_Christian_Trust#Emergency_accommodation_-_Bethany_House',
        url: 'http://www.bethanychristiantrust.com/services/emergency-resettlement/',
        twitter: '@_BethanyCT',
        males: true,
        females: true,
        minAge: 16,
        maxAge: 999,
        pets: false,
        active: true
    },{
        title: 'Castlecliff',
        location: {lat: 55.948042, lng: -3.197942},
        address: '25 Johnston Terrace',
        phone: '0131 225 1643',
        email: 'castlecliff@edinburgh.gov.uk',
        wiki: 'https://en.wikipedia.org/wiki/Politics_of_Edinburgh#Council_and_committees',
        url: 'https://www.edinburgh.gov.uk/directory_record/20741/castlecliff',
        twitter: '@Edinburgh_CC',
        males: true,
        females: true,
        minAge: 16,
        maxAge: 999,
        pets: true,
        active: true
    },{
        title: 'Cunningham House',
        location: {lat: 55.948521, lng: -3.188035},
        address: '205 Cowgate',
        phone: '0131 225 4795',
        email: 'info@crossreach.org.uk',
        wiki: 'https://en.wikipedia.org/wiki/Church_of_Scotland#Councils',
        url: 'http://www.crossreach.org.uk/cunningham-house',
        twitter: '@CrossReach',
        males: true,
        females: true,
        minAge: 18,
        maxAge: 65,
        pets: false,
        active: true
    },{
        title: 'Dunedin Harbour',
        location: {lat: 55.974320, lng: -3.172797},
        address: '4 Parliament Street',
        phone: '0131 624 5800',
        email: 'hostel@dunedincanmore.org.uk',
        wiki: 'https://en.wikipedia.org/wiki/Dunedin_Harbour',
        url: 'https://www.dunedincanmore.org.uk/2/dunedin-harbour',
        twitter: '@DunedinCanmore',
        males: true,
        females: true,
        minAge: 16,
        maxAge: 999,
        pets: true,
        active: true
    },{
        title: 'Keymoves',
        location: {lat: 55.950814, lng: -3.184032},
        address: '2 Cranston Street',
        phone: '0131 556 8939',
        email: 'info@keymoves.org.uk',
        wiki: 'https://en.wikipedia.org/wiki/Keymoves',
        url: 'http://www.keymoves.org.uk/',
        twitter: '',
        males: false,
        females: true,
        minAge: 18,
        maxAge: 999,
        pets: false,
        active: true
    },{
        title: 'Number Twenty',
        location: {lat: 55.958834, lng: -3.188510},
        address: '20 Broughton Place',
        phone: '0131 557 1739',
        email: 'lindam@foursquare.org.uk',
        wiki: 'https://en.wikipedia.org/wiki/Number_Twenty',
        url: 'http://www.foursquare.org.uk/our-services/accommodation-and-support/number-20/',
        twitter: '@FourSquareEdin',
        males: false,
        females: true,
        minAge: 16,
        maxAge: 21,
        pets: false,
        active: true
    },{
        title: 'Pleasance Lifehouse',
        location: {lat: 55.949095, lng: -3.183409},
        address: '1 The Pleasance',
        phone: '0131 556 9674',
        email: 'eastscotland@salvationarmy.org.uk',
        wiki: 'https://en.wikipedia.org/wiki/The_Salvation_Army',
        url: 'https://www.salvationarmy.org.uk/pleasance-lifehouse',
        twitter: '@salvationarmyuk',
        males: true,
        females: false,
        minAge: 18,
        maxAge: 70,
        pets: false,
        active: true
    },{
        title: 'Stopover',
        location: {lat: 55.944195, lng: -3.211942},
        address: '40 Grove Street',
        phone: '0131 229 6907',
        email: 'lindam@foursquare.org.uk',
        wiki: 'https://en.wikipedia.org/wiki/Stopover_Edinburgh',
        url: 'http://www.foursquare.org.uk/our-services/accommodation-and-support/stopover/',
        twitter: '@FourSquareEdin',
        males: true,
        females: true,
        minAge: 16,
        maxAge: 21,
        pets: false,
        active: true
    }
];